### PR TITLE
Update nodejs.yml

### PR DESCRIPTION
**Pull request by tiagomsmagalhaes**

### CODE REVIEW

**Comment by gabrielfurini** [comment]
Hey @tiagomsmagalhaes. Thanks for your contribution.
I've noticed you did not provide a description for this PR... Could you elaborate what is the purpose of it, please?

**Comment by tiagomsmagalhaes** [comment]
I have found a potential issue where, encoding a string and decoding the morse code of that string resulted in a different string i have entered.

I checked the test file, forked the repo, and experimented creating a Github Action that would run the test files on every push. The "mistake" was when I tried to merge the branch through PR, I made a PR on your repo.

**Comment by tiagomsmagalhaes** [comment]
You can check the failure https://github.com/tiagomsmagalhaes/morsee/runs/243303130

**Comment by gabrielfurini** [comment]
OK, I see...
If I am correct, you opened this PR by mistake, right? The best to do in this case is to close it then.

If your intention is to fix the issue you have found, you can open another PR. I would be glad to review and approve it.
On the other hand, if your intention is to report a problem, the best way of doing it is to open an issue.

**Comment by tiagomsmagalhaes** [comment]
If it would of your interest on having Github actions to automatically run the tests, this PR could be a start.

Nevertheless, I can open an issue regarding that bug I found. I haven't had the time to carefully look how the library works in order to determine If I am able to provide a fix to the issue

**Pull request closed without merging**
